"""Initial migration

Revision ID: 315dcd420a4f
Revises: 
Create Date: 2024-08-05 16:23:24.447881

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '315dcd420a4f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'permissions',
        sa.Column('permission_pk', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('permission_pk'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'roles',
        sa.Column('role_pk', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('role_pk'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'role_permissions',
        sa.Column(
            'role_permission_pk', sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column('role_pk', sa.Integer(), nullable=True),
        sa.Column('permission_pk', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['permission_pk'],
            ['permissions.permission_pk'],
        ),
        sa.ForeignKeyConstraint(
            ['role_pk'],
            ['roles.role_pk'],
        ),
        sa.PrimaryKeyConstraint('role_permission_pk'),
    )
    op.create_table(
        'users',
        sa.Column('user_pk', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('first_name', sa.String(), nullable=False),
        sa.Column('last_name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=True,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('role_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['role_id'],
            ['roles.role_pk'],
        ),
        sa.PrimaryKeyConstraint('user_pk'),
        sa.UniqueConstraint('email'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
