"""Added the is_verified field to the User table

Revision ID: 2b1a7e842365
Revises: b0c203e5aeec
Create Date: 2024-08-21 16:23:21.761812

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2b1a7e842365'
down_revision: Union[str, None] = 'b0c203e5aeec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'refresh_tokens', ['token'])
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.alter_column('users', 'is_active', existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active', existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_column('users', 'is_verified')
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    # ### end Alembic commands ###
