"""Initial migration

Revision ID: 64f5562bd56c
Revises: 
Create Date: 2024-08-01 23:44:19.124453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64f5562bd56c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('permission_pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('permission_pk'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('role_pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('role_pk'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_permissions',
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('permission', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission'], ['permissions.permission_pk'], ),
    sa.ForeignKeyConstraint(['role'], ['roles.role_pk'], ),
    sa.PrimaryKeyConstraint('role', 'permission')
    )
    op.create_table('users',
    sa.Column('user_pk', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['roles.role_pk'], ),
    sa.PrimaryKeyConstraint('user_pk')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_permissions')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
