"""updated role_permissions table

Revision ID: ae536998e688
Revises: 2b1a7e842365
Create Date: 2024-08-22 22:23:10.345424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae536998e688'
down_revision: Union[str, None] = '2b1a7e842365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('refresh_tokens_user_pk_fkey', 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_pk'], ['user_pk'], ondelete='CASCADE')
    op.add_column('role_permissions', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('role_permissions', 'role_pk',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('role_permissions', 'permission_pk',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('role_permissions_permission_pk_fkey', 'role_permissions', type_='foreignkey')
    op.drop_constraint('role_permissions_role_pk_fkey', 'role_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'role_permissions', 'roles', ['role_pk'], ['role_pk'], ondelete='CASCADE')
    op.create_foreign_key(None, 'role_permissions', 'permissions', ['permission_pk'], ['permission_pk'], ondelete='CASCADE')
    op.drop_column('role_permissions', 'role_permission_pk')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_permissions', sa.Column('role_permission_pk', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.create_foreign_key('role_permissions_role_pk_fkey', 'role_permissions', 'roles', ['role_pk'], ['role_pk'])
    op.create_foreign_key('role_permissions_permission_pk_fkey', 'role_permissions', 'permissions', ['permission_pk'], ['permission_pk'])
    op.alter_column('role_permissions', 'permission_pk',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('role_permissions', 'role_pk',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('role_permissions', 'created_at')
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key('refresh_tokens_user_pk_fkey', 'refresh_tokens', 'users', ['user_pk'], ['user_pk'])
    # ### end Alembic commands ###
